# 基本配置
site_dir: "site"
site_name: Josh's Blog   # 定义站点名称，会显示在网页的标题和导航栏中
copyright: 'Copyright &copy; 2023 <a href="http://joshzhong.top">赣ICP备2023014948号</a> '     # 设置版权信息，通常显示在网站的页脚


# Docs 
docs_dir: "docs"
# 主题配置
theme:
  language: 'zh'   # 设置网站的语言为中文
  name: 'material'   # 使用Material主题，这是一个流行的MkDocs主题，提供了丰富的样式和功能
  custom_dir: overrides
  icon:
    logo: 'material/google-downasaur'   # 设置网站的logo图标为Material主题中的GitHub图标
  include_search: true   # 启用&禁用搜索
  # 增加调整亮暗模式
  palette: 
    # Palette toggle for light mode
    - scheme: default   # 默认的配色方案
      primary: indigo    # 设置主色调颜色
      accent: blue   # 设置强调色
      toggle:
        icon: material/weather-night   # 切换图标设置为夜间模式的图标
        name: 切换到暗色模式
    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: 切换到亮色模式
  font:
    text: Roboto # 可选字体，保持简洁
    code: Roboto Mono
  # 主题功能
  features:   # 启用了多个Material主题的增强功能，这些功能主要围绕导航、搜索和代码块的显示进行改进
    - navigation.instant   # 页面不会跳转，而是像单页应用一样在当前页面内完成导航，提高页面响应速度和美观度
    - navigation.tabs   # 页面上方显示标签页，便于多页面导航
    - navigation.tracking   # 页面滚动时，导航栏会高亮显示当前页面所在位置
    - navigation.indexes   # 为页面生成一个基于标题的索引，通常显示在侧边栏，可以快速跳转到页面中的特定部分
    - navigation.sections   # 导航栏中的项目被分成不同的部分
    - navigation.expand   # 默认展开导航栏中的所有项目
    - navigation.prune   # 仅渲染当前页面的导航，简化导航结构
    - toc.follow   # 滚动的时候侧边栏自动跟随
    - navigation.top   # 在页面底部增加“返回顶部”按钮
    - search.suggest   # 启用搜索建议功能，用户输入时会显示匹配的结果
    - search.highlight   # 搜索结果中高亮显示匹配的内容
    - search.share   # 允许分享搜索结果的链接
    - navigation.footer   # 在页脚显示“下一章”的导航提示
    - content.code.copy   # 在代码段上方添加“复制代码”的按钮


markdown_extensions:
  - admonition        # 支持提示框、警告框等Admonition语法
  - def_list          # 支持定义列表（term: definition）
  - footnotes         # 支持脚注
  - abbr              # 支持缩略词
  - md_in_html        # 允许在HTML中嵌入Markdown
  - attr_list         # 支持为元素添加属性（如class、id）
  - toc:              # 自动生成目录
      permalink: true   # 目录标题旁边显示锚点链接符号
      toc_depth: 3     # 目录深度为三级标题
  - pymdownx.betterem # 改进斜体和加粗的解析，避免冲突
  - pymdownx.caret    # 支持插入 ^ 标记的上标语法
  - pymdownx.mark     # 支持 ==标记== 高亮文本
  - pymdownx.tilde    # 支持 ~~删除线~~
  - pymdownx.keys     # 支持键盘按键样式 `<kbd>`
  - pymdownx.critic   # 支持批注标记语法 {++新增++} {--删除--} {~~替换~~}
  - pymdownx.details  # 支持折叠内容块 `<details>`
  - pymdownx.inlinehilite  # 支持行内代码高亮，如 `==code==`
  - pymdownx.snippets     # 支持代码片段复用
  - pymdownx.superfences: # 支持更复杂的代码块（可嵌套）
      custom_fences:
        - name: mermaid     # 自定义Mermaid流程图代码块
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:   # 代码块高亮配置
      anchor_linenums: true     # 行号支持点击跳转
      linenums: true           # 显示行号
      use_pygments: true       # 使用 Pygments 作为高亮引擎
      pygments_lang_class: true # 在代码块增加语言类名
      auto_title: true         # 自动从代码块标题显示语言名
      linenums_style: pymdownx-inline  # 行号样式为内嵌（紧凑）
  - pymdownx.magiclink     # 自动识别 URL 和邮件，转成链接
  - pymdownx.smartsymbols  # 智能符号替换（如 -> 替换成 →）
  - pymdownx.arithmatex:   # 数学公式支持
      generic: true          # 兼容多种渲染引擎
  - pymdownx.tabbed:       # 支持标签页显示
      alternate_style: true     # 使用交替风格标签页
      combine_header_slug: true # 组合标题生成标签页ID
  - pymdownx.tasklist:     # 任务列表支持（带复选框）
      custom_checkbox: true     # 使用自定义复选框样式
      clickable_checkbox: true  # 复选框可点击切换
  - pymdownx.emoji:        # Emoji表情支持
      emoji_index: !!python/name:material.extensions.emoji.twemoji  # 使用 Twemoji 表情库
      emoji_generator: !!python/name:material.extensions.emoji.to_svg # 转成 SVG 格式的表情
  - meta                   # 支持文档元数据（meta）
  - tables                 # 支持Markdown表格



plugins:  # 配置MkDocs的插件
  - rss:  # 启用RSS插件
      enabled: True  # 启用RSS订阅
      image: https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Feed-icon.svg/128px-Feed-icon.svg.png  # RSS订阅图标的URL
      pretty_print: True  # 格式化RSS输出
      length: 1000  # 设置摘要的长度
      date_from_meta:  # 从元数据中获取文章的日期
          as_creation: "date"  # 将文章的创建日期视为发布日期
          as_update: "date"  # 将文章的更新日期视为发布日期
      abstract_chars_count: -1  # 设置摘要的字符数限制
      match_path: "(blog/posts|flinks|galaxy|message|note|readme|tech|yuque)/.*"  # RSS订阅包含的路径模式
  - glightbox:  # 启用gLightbox插件
      auto_caption: false  # 自动生成图片标题
      caption_position: bottom  # 图片标题显示在底部
  - search:  # 启用搜索插件
      lang:
          - en  # 支持英文搜索
          - zh  # 支持中文搜索
  - git-revision-date-localized:  # 启用Git本地化修订日期插件
      type: iso_date  # 显示ISO格式的日期
      timezone: Asia/Shanghai  # 设置时区为上海时间
      fallback_to_build_date: true  # 如果没有Git日期则使用构建日期
      exclude:  # 排除某些路径不显示修订日期
          - blog/archive/*  # 排除博客归档文件
          - blog/category/*  # 排除博客分类文件
  - awesome-pages:  # 启用Awesome Pages插件
      order: asc  # 设置页面的默认排序方式为降序
      sort_type: natural  # 使用自然排序
      order_by: filename  # 按文件名排序



extra_javascript:
  # - javascripts/extra.js #自定义javascript
  - https://cdn.jsdelivr.net/gh/Wcowin/Wcowin.github.io@main/docs/javascripts/extra.js  # extra的cdn
  - javascripts/mathjax.js #Latex支持
  - https://polyfill.io/v3/polyfill.min.js?features=es6 #Latex支持
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js #Latex支持
  # - ckplayer/js/ckplayer.js #播放器配置
  # - https://cdn.jsdelivr.net/npm/gitalk@latest/dist/gitalk.min.js  #gitalk支持
  - https://cdn.jsdelivr.net/npm/mermaid@10.0.2/dist/add-html-label-6e56ed67.min.js #忘了


extra_css:
  - css/extra.css  # 引用自定义的CSS文件

  - https://cdn.staticfile.org/font-awesome/4.7.0/css/font-awesome.css # font-awesome表情支持
  # - https://cdnjs.cloudflare.com/ajax/libs/social-share.js/1.0.16/css/share.min.css  #分享支持
  
  - https://cdn.jsdelivr.net/npm/lxgw-wenkai-webfont@1.1.0/style.css #字体
  # - https://cdn.jsdelivr.net/npm/lxgw-wenkai-lite-webfont@1.1.0/style.css #字体
  # - https://cdn.jsdelivr.net/npm/lxgw-wenkai-tc-webfont@1.0.0/style.css  #字体
  # - https://cdn.jsdelivr.net/npm/lxgw-wenkai-screen-webfont@1.1.0/style.css  #字体
