--- 
# ansible_playbook install_openvpn.yml

- import_playbook: uninstall-rpm-openssl.yml
- import_playbook: install-openssl.yml
- import_playbook: install-libnl3.yml
- import_playbook: install-go.yml

- name: Install OpenVPN Server 
  hosts: centos7
  become: true
  vars:
    openvpn_version: openvpn-2.6.11
    openvpn_download_path: /usr/local/src
    openvpn_install_path: /usr/local/openvpn
    openvpn_download_url: https://swupdate.openvpn.org/community/releases/openvpn-2.6.11.tar.gz

  tasks:
    - name: Detecting Operating System
      fail:
        msg: "Only Supports the Redhat family. Currently{{ ansible_distribution }}-{{ ansible_distribution_version }} (Family: {{ ansible_os_family }})"
      when: ansible_os_family != "RedHat"

    - name: Check If OpenVPN source is not installed
      stat:
        path: "{{ openvpn_install_path }}"
      register: openvpn_directory
      ignore_errors: true

    - name: If OpenVPN source is already installed, skip it
      fail:
        msg: " OpenVPN is already installed, skipping..."
      when: openvpn_directory.stat.exists

    - name: Stop Firewalld
      service:
        name: firewalld
        state: stopped
        enabled: no

    - name: Disable SELinux
      shell: setenforce 0 && sed -i 's/enforcing/disabled/' /etc/selinux/config
      when: ansible_selinux.status == "enabled"

    - name: Enable IPv4 Net 
      shell: |
        echo "net.ipv4.ip_forward = 1" >> /etc/sysctl.conf
        sysctl -p

    - name: Install Rely
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - autoconf
        - automake
        - bison
        - flex
        - cmake
        - iproute
        - lz4-devel
        - lzo-devel
        - pam-devel
        - p11-kit-devel
        - libselinux-devel
        - systemd-devel
        - libcap-ng-devel
        - pkcs11-helper-devel
        - sqlite-devel
        - libtool
        - libtool-ltdl

    # - name: Download OpenVPN Source Package
    #   shell:
    #     wget https://swupdate.openvpn.org/community/releases/openvpn-2.6.11.tar.gz --no-check-certificate -P /usr/local/src

    - name: Download OpenVPN Source Package
      #shell: wget https://swupdate.openvpn.org/community/releases/openvpn-2.6.11.tar.gz --no-check-certificate
      get_url:
        url: http://swupdate.openvpn.org/community/releases/openvpn-2.6.11.tar.gz
        dest: /usr/local/src
        mode: '0644'

    - name: Unarchive OpenVPN Source Package
      unarchive:
        src: /usr/local/src/openvpn-2.6.11.tar.gz
        dest: /usr/local/src
        remote_src: yes
    
    - name: Configure OpenVPN
      command: | 
        ./configure \
        --prefix=/usr/local/openvpn \
        --enable-lzo \
        --enable-lz4 \
        --enable-debug \
        --enable-management \
        --enable-async_push \
        --enable-plugins \
        --enable-port-share \
        --enable-static \
        --enable-plugin-auth-pam \
        --enable-pam-dlopen \
        --enable-silent-rules \
        --enable-x509-alt-username \
        --enable-pkcs11 \
        --enable-selinux \
        --with-crypto-library=openssl \
        --with-gnu-ld \
        --with-openssl-engine=auto \
        --enable-iproute2 \
        --enable-systemd
      args:
        chdir: /usr/local/src/openvpn-2.6.11

    - name: Make OpenVPN
      shell: |
        make -j $(nproc)
      args:
        chdir: /usr/local/src/openvpn-2.6.11

    - name: Install OpenVPN
      shell: |
        make install
      args:
        chdir: /usr/local/src/openvpn-2.6.11 

    - name: Create OpenVPN Configuration Directory
      file:
        path: /usr/local/openvpn/config
        state: directory
    
    - name: Setup OpenVPN Service
      copy:
        dest: /usr/lib/systemd/system/openvpn.service
        mode: 0644
        content: |
          [Unit]
          Description=OpenVPN service for server
          After=syslog.target network-online.target
          Wants=network-online.target
          Documentation=man:openvpn(8)
          Documentation=https://community.openvpn.net/openvpn/wiki/Openvpn24ManPage
          Documentation=https://community.openvpn.net/openvpn/wiki/HOWTO

          [Service]
          Type=notify
          PrivateTmp=true
          WorkingDirectory={{ openvpn_install_dir }}
          ExecStart={{ openvpn_install_dir }}/sbin/openvpn --config {{ openvpn_install_dir }}/config/{{ openvpn_ovpn_file }}
          CapabilityBoundingSet=CAP_IPC_LOCK CAP_NET_ADMIN CAP_NET_BIND_SERVICE CAP_NET_RAW CAP_SETGID CAP_SETUID CAP_SETPCAP CAP_SYS_CHROOT CAP_DAC_OVERRIDE CAP_AUDIT_WRITE
          LimitNPROC=10
          DeviceAllow=/dev/null rw
          DeviceAllow=/dev/net/tun rw
          ProtectHome=true
          KillMode=process
          RestartSec=5s
          Restart=always

          [Install]
          WantedBy=multi-user.target        

    - name: Reload systemd to apply the new service
      command: systemctl daemon-reload

    - name: Enable and start OpenVPN service
      systemd:
        name: openvpn
        enabled: yes
        state: started

    - name: Create Link
      file:
        src: /usr/local/openvpn/sbin/openvpn
        dest: /usr/sbin/openvpn
        state: link
        force: yes

    - name: Verify OpenVPN installation
      shell: openvpn --version
      register: openvpn_version
      ignore_errors: true
    
    - name: If OpenVPN is not installed, fail the play
      fail:
        msg: "OpenVPN installation failed"
        when: openvpn_version.rc != 0
    
    - name: Clean File
      file: 
        path: "{{ item }}"
        state: absent
      loop:
        - /usr/local/src/openvpn-2.6.11.tar.gz
        - /usr/local/src/openvpn-2.6.11
    
  

