version: "3"
services:
  navidrome:
    image: deluan/navidrome:latest
    ports:
      - "10533:4533"
    restart: unless-stopped
    environment:
      ND_ENABLETRANSCODINGCONFIG: true
      ND_TRANSCODINGCACHESIZE: 0
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info  
      ND_SESSIONTIMEOUT: 24h
      ND_BASEURL: ""
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
    volumes:
      - "/data/navidrome/data:/data"
      - "/data/navidrome/music:/music:ro"

  miniserve:
    image: svenstaro/miniserve:latest
    depends_on:
      - navidrome
    ports:
      - "10534:8080"
    environment:
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
    volumes:
      - "/data/navidrome/music:/downloads"
    command: "-r -z -u -q -p 8080 -a admin:Sunline2024 /downloads"
    restart: unless-stopped

