version: "3.2"
services:
  nginxWebUi-server:
    image: cym1102/nginxwebui:latest
    container_name: nginxwebui
    restart: always
    volumes:
      - type: bind
        source: "/data/nginxWebUI"
        target: "/home/nginxWebUI"
    environment:
      BOOT_OPTIONS: "--server.port=10180"
    privileged: true
    network_mode: "host"
