- name: Yum Install Samba
  hosts: centos7
  become: true
  tasks:
    - name: Install Samba
      yum:
        name: samba 
        state: present

    - name: Delete Samba Config
      file:
        path: /etc/samba/smb.conf
        state: absent

    - name: Create Samba Group
      group:
        name: "{{ item }}"
        state: present
      loop:
        - software
        - josh

    - name: Create Samba User
      user:
        name: "{{ item }}"
        state: present
        group: software
      loop:
        - josh

    - name: Create Samba Share Directory
      file:
        path: /data/software
        state: directory
        mode: '0755'
        owner: software
        group: software
        recurse: yes

    - name: Create Samba Config in /etc/smb.conf
      template:
        src: /data/ansible/templates/samba.conf.j2
        dest: /etc/samba/smb.conf
        mode: '0644'

    - name: Disable Firewalld Service
      shell: systemctl stop firewalld && systemctl disable firewalld

    - name: Temporarily disable SELinux
      shell: setenforce 0
      when: ansible_selinux.status == "enabled"

    - name: Permanently disable SELinux
      shell: sed -i 's/SELINUX=enforcing/SELINUX=disabled/g' /etc/selinux/config


    - name: Service Start Samba
      service:
        name: smb
        state: started

    - name: Service Enable Samba
      service:
        name: smb
        enabled: true

    # 需要安装python3和 python3下的依赖库pexpect
    # - name: Set Samba user password
    #   expect:
    #     command: smbpasswd -a josh
    #     responses:
    #       "New SMB password:" : "josh2024"
    #       "Retype new SMB password:" : "josh2024"
    #     timeout: 30

    - name: Set Samba user password
      community.general.samba_user:
        name: josh
        password: josh2024
        state: present

    - name: Restart Samba
      service:
        name: smb
        state: restarted
