- name: Install Go Tool
  hosts: centos7
  become: true
  tasks:
    - name:  Go Install Bee Tool 
      shell: go install github.com/beego/bee/v2@develop

    - name: Go Install Qrencode
      shell: |
        cd /opt/openvpn-ui/build
        git clone https://github.com/d3vilh/qrencode
        go env -w GOFLAGS="-buildvcs=false"
        cd /opt/openvpn-ui
        bee pack -exr='^vendor|^ace.tar.bz2|^data.db|^build|^README.md|^docs'
        mkdir /opt/openvpn-ui/openvpn-ui-pack
        tar -xzf openvpn-ui.tar.gz -C openvpn-ui-pack
        cd openvpn-ui-pack
        cp openvpn-ui ../
        cp openvpn-ui $(go env GOPATH)/bin
        cd ..
        rm -rf openvpn-ui-pack && rm -f openvpn-ui.tar.gz