- name: Yum Install Samba
  hosts: centos7
  become: true
  vars_files:
    - /data/ansible/samba_vars.yml
  tasks:
    - name: Disable Firewalld Service
      shell: systemctl stop firewalld && systemctl disable firewalld

    - name: Disable SELinux
      shell: setenforce 0 && sed -i 's/SELINUX=enforcing/SELINUX=disabled/g' /etc/selinux/config
      when: ansible_selinux.status == "enabled"

    - name: Install Samba
      yum:
        name: samba 
        state: present

    - name: Configure Samba settings in smb.conf
      template:
        src: /data/ansible/templates/smb.conf.j2
        dest: /etc/samba/smb.conf
        mode: 0644

    - name: Create Samba Group
      group:
        name: "{{ allowed_group }}"
        state: present

    - name: Create System User
      user:
        name: "{{ samba_user }}"
        group: "{{ allowed_group }}"
        shell: /sbin/nologin
        system: no 
        create_home: no

    - name: Create Samba User
      command: smbpasswd -s -a {{ samba_user }}
      args: 
        stdin: "{{ samba_passwd }}\n{{ samba_passwd }}"

    - name: Create Samba Share Directory
      file:
        path: "{{ share_dir }}"
        state: directory
        mode: '0755'
        owner: "{{ samba_user }}"
        group: "{{ allowed_group }}"
        recurse: yes

    - name: Service Start Samba
      service:
        name: smb
        state: started
        enabled: true