version: "3"

networks:
  gitea:
    external: false

services:
  server:
    image: gitea/gitea
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=db:3306
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=Sunline2024
    restart: always
    networks:
      - gitea
    volumes:
      - /data/gitea:/data/gitea
    ports:
      - "3000:3000"
      - "2222:22"
    depends_on:
      - db

  db:
    image: docker.io/library/mysql:8
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=Sunline2024
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=Sunline2024
      - MYSQL_DATABASE=gitea
    networks:
      - gitea
    volumes:
      - /data/mysql:/var/lib/mysql