cat > /data/woodwhales-music/docker-compose.yml <<'EOF'
version: '3.8'
services:
  woodwhales-music:
    image: woodwhales/woodwhales-music
    container_name: woodwhales-music
    networks:
      - woodwhales-music_network
    ports:
      - 8084:8084
    restart: always
    environment:
      - MYSQL_HOST=10.22.51.65
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=open-music
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=Sunline2024
      - "SPRING_DATASOURCE_URL=jdbc:mysql://10.22.51.65:3306/open-music?allowPublicKeyRetrieval=true&useSSL=false"
      - SYSTEM_INIT_PASSWORD=Sunline2024
    volumes:
      - /data/woodwhales-music:/app/data
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    container_name: mysql
    networks:
      - woodwhales-music_network
    ports:
      - 3306:3306
    restart: always
    privileged: true
    environment:
      - MYSQL_ROOT_PASSWORD=Sunline2024
      - MYSQL_DATABASE=open-music
    volumes:
      - /data/woodwhales-music/mysql/log:/var/log/mysql
      - /data/woodwhales-music/mysql/data:/var/lib/mysql
      - /data/woodwhales-music/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - /data/woodwhales-music/doc/sql/open_music_data.sql:/docker-entrypoint-initdb.d/db.sql


volumes:
  mysql_data:
networks:
  woodwhales-music_network:
    name: woodwhales-music_network
    ipam:
      driver: default
      config:
        - subnet: 172.103.0.0/16
EOF